
(defpackage :simian.rails-generator.unparser
  (:use
   :cl
   :unparser :interrogation :entity :attribute :relationship :foundation :interface :formula :utilities
   )
  (:nicknames :rails-unparser)
  (:export
   #:*nested-attribute-title-class*
   #:*svg-delete-icon*
   #:*svg-view-icon*
   #:*svg-edit-icon*
   #:*svg-list-icon*
   #:*svg-add-icon*
   #:*error-list-style*
   #:*user-error-feedback-style*
   #:*simple-table-layouts?*
   #:*justify-grid-layouts?*
   #:*crud-page-title-class*
   #:*datagrid-title*
   #:*datasheet-title*
   #:*datasheet-class*
   #:*record-context-class*
   #:*record-context-section-class*
   #:*datasheet-content-class*
   #:*datasheet-line-class*
   #:*datasheet-element-class*
   #:*update-form-class*
   #:*update-form-line-class*
   #:*update-form-element-class*
   #:*data-listing-class*
   #:*list-body-class*
   #:*list-row-class*
   #:*list-element-class*
   #:*heading-row-class*
   #:*heading-element-class*
   #:*nested-form-class*
   #:*default-form-field-class*
   #:*form-submit-button-class*
   #:*delete-button-class*
   #:*delete-nested-attribute-class*
   #:*add-nested-attribute-class*
   #:*link-button-class*
   #:*default-form-label-class*
   #:*default-form-field-class*
   #:*default-form-collection-class*
   #:*default-form-element-class*
   #:action-label
   #:datasheet-item
   #:calculate-item-width
   #:comment-out
   #:comment-with-warning
   #:controller-name
   #:crud-page-heading
   #:data-list-heading
   #:data-list-row
   #:data-list-rows
   #:data-list-element
   #:format-data-context
   #:format-data-listing
   #:format-datasheet
   #:format-file-notice
   #:format-update-form
   #:implement-as-string?
   #:instance-name
   #:indent-block
   #:make-indent
   #:make-linked-element
   #:model-name
   #:model-plural
   #:my-side
   #:path-method-name
   #:schema-name
   #:t.prevented-saving
   #:t.add
   #:t.success
   #:t.show
   #:t.edit
   #:t.new
   #:t.error
   #:t.delete
   #:t.list
   #:t.no-data
   #:t.no-parent
   #:t.delete-confirmation
   #:t.delete-warning
   #:t.name
   #:t.long-name
   #:t.short-name
   #:t.long-plural
   #:t.short-plural
   #:t.button-title
   #:translate
   #:translation
   #:ui-label
   #:unparse-attribute-references
   #:unparse-attribute-value
   #:unparse-datatype
   #:unparse-callback-registration
   #:unparse-core-element
   #:unparse-default-meta-data
   #:unparse-default-value-expression
   #:unparse-derived-attribute
   #:unparse-erb
   #:unparse-find_calendar_entities
   #:unparse-form-element
   #:unparse-form-object-id
   #:unparse-formatting
   #:unparse-model-association
   #:unparse-model-validation
   #:unparse-namespace
   #:unparse-path
   #:unparse-path-method-call
   #:unparse-referential-collection
   #:unparse-summary-attribute
   #:unparse-summary-expression
   #:unparse-table-association
   #:unparse-template-element
   #:unparse-template-expression
   #:unparse-template-link
   #:unparse-url-heirarchy
   #:unparse-validation-constraint
   ))

;;;===========================================================================
;;; Local variables:
;;; tab-width: 4
;;; indent-tabs-mode: nil
;;; End:
